spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db9
    username: root
    password: 2003
    driver-class-name: com.mysql.cj.jdbc.Driver
  

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
#logging:
#  file:
#    name: log/person.log
server :
  port: 9090